{% set version = "11.0.0" %}

package:
  name: openvdb
  version: {{ version }}

source:
  url: https://github.com/AcademySoftwareFoundation/openvdb/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6314ff1db057ea90050763e7b7d7ed86d8224fcd42a82cdbb9c515e001b96c74
  patches:
    - 0001-Replace-ssize_t-with-Py_ssize_t.patch

build:
  number: 1
  skip: true  # [py<39]
  run_exports:
    - {{ pin_subpackage('openvdb', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - pybind11                               # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - sysroot_linux-64 2.17                  # [linux64]

  host:
    - blosc
    - libboost-devel
    - jemalloc  # [unix]
    - numpy
    - python
    - tbb-devel
    - zlib
    - pybind11

  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  requires:
    - numpy

  commands:
    - test -f ${PREFIX}/bin/vdb_print  # [unix]
    - test -f ${PREFIX}/include/openvdb/openvdb.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/OpenVDB/FindOpenVDB.cmake  # [unix]
    - test -f ${PREFIX}/lib/libopenvdb${SHLIB_EXT}.{{ version }}  # [unix]
    - test -f ${PREFIX}/lib/libopenvdb${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\openvdb%SHLIB_EXT% exit 1  # [win]
    - if not exist %LIBRARY_BIN%\vdb_print.exe exit 1  # [win]
    - if not exist %LIBRARY_LIB%\openvdb.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\openvdb\openvdb.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\OpenVDB\FindOpenVDB.cmake exit 1  # [win]
    - vdb_print --help
    # test numpy support
    - python -c "import pyopenvdb; import numpy; grid = pyopenvdb.FloatGrid(); grid.copyFromArray(numpy.random.rand(200, 200, 200))"
  imports:
    - pyopenvdb

about:
  home: https://github.com/AcademySoftwareFoundation/openvdb
  summary: 'OpenVDB - Sparse volume data structure and tools'
  description: |
    OpenVDB is an open source C++ library comprising a novel hierarchical data structure and a large suite of tools for the efficient storage and manipulation of sparse volumetric data discretized on three-dimensional grids. It was developed by DreamWorks Animation for use in volumetric applications typically encountered in feature film production.
  license: MPL-2.0
  license_file: LICENSE
  dev_url: https://github.com/AcademySoftwareFoundation/openvdb

extra:
  recipe-maintainers:
    - versatran01
    - tetov
